# Generated by Django 3.2.10 on 2023-12-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_description', models.CharField(max_length=255)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
