# Generated by Django 3.2.10 on 2023-12-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0002_userphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
